name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  intl: ^0.20.2
  device_info_plus: ^11.5.0
  permission_handler: ^12.0.1
  get: ^4.7.2
  package_info_plus: ^8.3.1
  floating_draggable_widget: ^2.3.0
  searchfield: ^1.3.3
  connectivity_plus: ^6.1.5
  http: ^1.5.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  shimmer: ^3.0.0
  flutter_typeahead: ^5.2.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5
  flex_color_scheme: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/images/png/
    - assets/images/svg/
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf

  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-SemiBold.ttf
        - asset: assets/fonts/NotoSans-Thin.ttf